export default {
    type: 'good',
    version: 'good_2',
    info: {
        values: [
            {
                name: '商品名称',
                coverImg: '/img/goodPhoto.png',
                activityPrice: 2999,
                buttonColor1: '#fff',
                buttonColor2: '#bb9d77',
                buttonTextColor1: '#bb9d77',
                buttonTextColor2: '#fff',
                buttonBorderColor1: '#bb9d77',
                buttonBorderColor2: '#bb9d77',
                nameColor: '#535353',
                priceColor: '#b83f3f',
                bcColor: '#fff',
                bindGood: {},
            },
            {
                name: '商品名称',
                coverImg: '/img/goodPhoto.png',
                activityPrice: 2999,
                buttonColor1: '#fff',
                buttonColor2: '#bb9d77',
                buttonTextColor1: '#bb9d77',
                buttonTextColor2: '#fff',
                buttonBorderColor1: '#bb9d77',
                buttonBorderColor2: '#bb9d77',
                nameColor: '#535353',
                priceColor: '#b83f3f',
                bcColor: '#fff',
                bindGood: {},
            },
            {
                name: '商品名称',
                coverImg: '/img/goodPhoto.png',
                activityPrice: 2999,
                buttonColor1: '#fff',
                buttonColor2: '#bb9d77',
                buttonTextColor1: '#bb9d77',
                buttonTextColor2: '#fff',
                buttonBorderColor1: '#bb9d77',
                buttonBorderColor2: '#bb9d77',
                nameColor: '#535353',
                priceColor: '#b83f3f',
                bcColor: '#fff',
                bindGood: {},
            },
            {
                name: '商品名称',
                coverImg: '/img/goodPhoto.png',
                activityPrice: 2999,
                buttonColor1: '#fff',
                buttonColor2: '#bb9d77',
                buttonTextColor1: '#bb9d77',
                buttonTextColor2: '#fff',
                buttonBorderColor1: '#bb9d77',
                buttonBorderColor2: '#bb9d77',
                nameColor: '#535353',
                priceColor: '#b83f3f',
                bcColor: '#fff',
                bindGood: {},
            }
        ]
    }
}